export { default as Dashboard } from './pages/Dashboard'
export { default as Tables } from './pages/TablesPage'
export { default as Orders } from './pages/OrdersPage'
export { default as MenuPage } from './pages/MenuPage'
export { default as Customers } from './pages/CustomersPage'
export { default as Reports } from './pages/ReportsPage'
